//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discharge
    {
        public long id { get; set; }
        public System.DateTime dischargeDate { get; set; }
        public string treatment { get; set; }
        public decimal amount { get; set; }
        public bool isDeleted { get; set; }
        public long doctorId { get; set; }
        public long admissionId { get; set; }
    
        public virtual Admission Admission { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
